services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      DATABASE_NAME: /app/data/db.sqlite3
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME:-admin}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD:-admin12345}
    volumes:
      - inventory_data:/app/data

volumes:
  inventory_data:
